### PR TITLE
Added util.html, fixed PUT and POST

### LINKED ISSUE #5: Update or Edit courses
- [x] Added one route with put method
- [x] Read the entire file
- [x] Validate the user input
- [x] Change the course name with the new course name
- [x] push the changes if these are valid to the file content 
- [x]  write the final changes to the database

### LINKED ISSUE #8: Final touches
- [x] Check if everything is fine

### PR DESCRIPTION
**Pull request by bermarte**
I have added a utility to interact with the back-end and changed the PUT function as well.

### CODE REVIEW

**Comment by bermarte** [comment]
I added a utility to interact with the backend and also changed the PUT function due to a bug. The POST function should also be correct. The problem is again related to the id series. When there are jumps it does not work well, as in the 1,2,4,5 series (where 3 is missing). This utility will ask you if you want to use the local DB or the one on Heroku (the end-point is **/util**).

**Comment by bermarte** [comment]
### why we need to change the POST function

I have added util.html, which is a page to interact with the backend, and also changed the PUT function due to a bug. The POST function should also be fixed. The problem is again related to the id series. When there are jumps it does not work well. This utility will ask if you want to use the local DB or the one on Heroku.

**POST Example**  if we have:
```
[
   {
      "id": 1,
      "name": "HYF"
   },
   {
      "id": 2,
      "name": "Mosh"
   },
   {
      "id": 3,
      "name": "Becode"
   },
   {
      "id": 4,
      "name": "new course"
   },
   {
      "id": 5,
      "name": "new course"
   },
   {
      "id": 6,
      "name": "new course"
   },
   {
      "id": 8,
      "name": "ABC"
   },
   {
      "id": 9,
      "name": "ABC 2"
   }
]
```
Instead of using
- `id: parsedCourses.length + 1 ` that gives **9**
- we need to take the last element of `parsedCourses`, take the id value, and add 1 to it
` parsedCourses[parsedCourses.length - 1]['id']+1`  result **10**

**Comment by bermarte** [comment]
Let's try to Rebase and Merge at the end.

**Review by AnisyaPurnama — APPROVED** [review]
😮

**Review by KrystynaMil — COMMENTED** [review]
Great work with util.html . But I tried to test it and doesn't work for me....

**Comment by bermarte** [comment]
@KrystynaMil We should check it together. 

Before running util.html you should start the server by running `npm run start` or `npm run watch`

**Comment by KrystynaMil** [comment]
Ok, I will check it out ! Thanks @bermarte

**Comment by KrystynaMil** [comment]
When I try to run get course/courses etc... buttons on util.html  I  have this types of error:
SyntaxError: Unexpected token S in JSON at position 0,
We can have a look on it tomorrow all together ....Maybe I am doing something wrong...

**Comment by bermarte** [comment]
@KrystynaMil Thank you, you are right.

**Review by KrystynaMil — APPROVED** [review]
Works very well !!! Thank you !

**Pull request merged**
